
services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: melbeez
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_service
    environment:
      AWS_S3_KEY: ${AWS_S3_KEY}
      AWS_S3_SECRET: ${AWS_S3_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      MEDIA_STORE: ${MEDIA_STORE}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
